// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/process.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNKNOWN       ProcessState = 0
	ProcessState_PROCESS_STATE_STOP          ProcessState = 1
	ProcessState_PROCESS_STATE_RUNNING       ProcessState = 2
	ProcessState_PROCESS_STATE_NEEDS_RESTART ProcessState = 3
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNKNOWN",
		1: "PROCESS_STATE_STOP",
		2: "PROCESS_STATE_RUNNING",
		3: "PROCESS_STATE_NEEDS_RESTART",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNKNOWN":       0,
		"PROCESS_STATE_STOP":          1,
		"PROCESS_STATE_RUNNING":       2,
		"PROCESS_STATE_NEEDS_RESTART": 3,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_process_proto_enumTypes[0].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_proto_process_proto_enumTypes[0]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Process struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Command     []string               `protobuf:"bytes,2,rep,name=command"`
	xxx_hidden_Dir         *string                `protobuf:"bytes,3,opt,name=dir"`
	xxx_hidden_LogFile     *string                `protobuf:"bytes,4,opt,name=log_file,json=logFile"`
	xxx_hidden_Watch       bool                   `protobuf:"varint,5,opt,name=watch"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_proto_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Process) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Process) GetCommand() []string {
	if x != nil {
		return x.xxx_hidden_Command
	}
	return nil
}

func (x *Process) GetDir() string {
	if x != nil {
		if x.xxx_hidden_Dir != nil {
			return *x.xxx_hidden_Dir
		}
		return ""
	}
	return ""
}

func (x *Process) GetLogFile() string {
	if x != nil {
		if x.xxx_hidden_LogFile != nil {
			return *x.xxx_hidden_LogFile
		}
		return ""
	}
	return ""
}

func (x *Process) GetWatch() bool {
	if x != nil {
		return x.xxx_hidden_Watch
	}
	return false
}

func (x *Process) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Process) SetCommand(v []string) {
	x.xxx_hidden_Command = v
}

func (x *Process) SetDir(v string) {
	x.xxx_hidden_Dir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Process) SetLogFile(v string) {
	x.xxx_hidden_LogFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Process) SetWatch(v bool) {
	x.xxx_hidden_Watch = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Process) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Process) HasDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Process) HasLogFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Process) HasWatch() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Process) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Process) ClearDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Dir = nil
}

func (x *Process) ClearLogFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LogFile = nil
}

func (x *Process) ClearWatch() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Watch = false
}

type Process_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    *string
	Command []string
	Dir     *string
	LogFile *string
	Watch   *bool
}

func (b0 Process_builder) Build() *Process {
	m0 := &Process{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Command = b.Command
	if b.Dir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Dir = b.Dir
	}
	if b.LogFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_LogFile = b.LogFile
	}
	if b.Watch != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Watch = *b.Watch
	}
	return m0
}

type ProcessStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_StartedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt"`
	xxx_hidden_State       ProcessState           `protobuf:"varint,3,opt,name=state,enum=process.ProcessState"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_proto_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessStatus) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ProcessStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *ProcessStatus) GetState() ProcessState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_State
		}
	}
	return ProcessState_PROCESS_STATE_UNKNOWN
}

func (x *ProcessStatus) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ProcessStatus) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *ProcessStatus) SetState(v ProcessState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ProcessStatus) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProcessStatus) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *ProcessStatus) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProcessStatus) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ProcessStatus) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *ProcessStatus) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_State = ProcessState_PROCESS_STATE_UNKNOWN
}

type ProcessStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name      *string
	StartedAt *timestamppb.Timestamp
	State     *ProcessState
}

func (b0 ProcessStatus_builder) Build() *ProcessStatus {
	m0 := &ProcessStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_StartedAt = b.StartedAt
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_State = *b.State
	}
	return m0
}

type RequestStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestStatus) Reset() {
	*x = RequestStatus{}
	mi := &file_proto_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStatus) ProtoMessage() {}

func (x *RequestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestStatus) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RequestStatus) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RequestStatus) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestStatus) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type RequestStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 RequestStatus_builder) Build() *RequestStatus {
	m0 := &RequestStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ResponseStatus struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Processes *[]*ProcessStatus      `protobuf:"bytes,1,rep,name=processes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_proto_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseStatus) GetProcesses() []*ProcessStatus {
	if x != nil {
		if x.xxx_hidden_Processes != nil {
			return *x.xxx_hidden_Processes
		}
	}
	return nil
}

func (x *ResponseStatus) SetProcesses(v []*ProcessStatus) {
	x.xxx_hidden_Processes = &v
}

type ResponseStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Processes []*ProcessStatus
}

func (b0 ResponseStatus_builder) Build() *ResponseStatus {
	m0 := &ResponseStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Processes = &b.Processes
	return m0
}

type RequestStart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestStart) Reset() {
	*x = RequestStart{}
	mi := &file_proto_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStart) ProtoMessage() {}

func (x *RequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestStart) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RequestStart) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RequestStart) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestStart) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type RequestStart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 RequestStart_builder) Build() *RequestStart {
	m0 := &RequestStart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ResponseStart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ok          bool                   `protobuf:"varint,1,opt,name=ok"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResponseStart) Reset() {
	*x = ResponseStart{}
	mi := &file_proto_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStart) ProtoMessage() {}

func (x *ResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseStart) GetOk() bool {
	if x != nil {
		return x.xxx_hidden_Ok
	}
	return false
}

func (x *ResponseStart) SetOk(v bool) {
	x.xxx_hidden_Ok = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ResponseStart) HasOk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResponseStart) ClearOk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ok = false
}

type ResponseStart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ok *bool
}

func (b0 ResponseStart_builder) Build() *ResponseStart {
	m0 := &ResponseStart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ok != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Ok = *b.Ok
	}
	return m0
}

type RequestStop struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestStop) Reset() {
	*x = RequestStop{}
	mi := &file_proto_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStop) ProtoMessage() {}

func (x *RequestStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestStop) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RequestStop) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RequestStop) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestStop) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type RequestStop_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 RequestStop_builder) Build() *RequestStop {
	m0 := &RequestStop{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ResponseStop struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ok          bool                   `protobuf:"varint,1,opt,name=ok"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResponseStop) Reset() {
	*x = ResponseStop{}
	mi := &file_proto_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStop) ProtoMessage() {}

func (x *ResponseStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseStop) GetOk() bool {
	if x != nil {
		return x.xxx_hidden_Ok
	}
	return false
}

func (x *ResponseStop) SetOk(v bool) {
	x.xxx_hidden_Ok = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ResponseStop) HasOk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResponseStop) ClearOk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ok = false
}

type ResponseStop_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ok *bool
}

func (b0 ResponseStop_builder) Build() *ResponseStop {
	m0 := &ResponseStop{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ok != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Ok = *b.Ok
	}
	return m0
}

type RequestRestart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestRestart) Reset() {
	*x = RequestRestart{}
	mi := &file_proto_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRestart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRestart) ProtoMessage() {}

func (x *RequestRestart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestRestart) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RequestRestart) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RequestRestart) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestRestart) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type RequestRestart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 RequestRestart_builder) Build() *RequestRestart {
	m0 := &RequestRestart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ResponseRestart struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRestart) Reset() {
	*x = ResponseRestart{}
	mi := &file_proto_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRestart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRestart) ProtoMessage() {}

func (x *ResponseRestart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResponseRestart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResponseRestart_builder) Build() *ResponseRestart {
	m0 := &ResponseRestart{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RequestLogs struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestLogs) Reset() {
	*x = RequestLogs{}
	mi := &file_proto_process_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLogs) ProtoMessage() {}

func (x *RequestLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestLogs) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RequestLogs) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RequestLogs) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestLogs) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type RequestLogs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 RequestLogs_builder) Build() *RequestLogs {
	m0 := &RequestLogs{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ResponseLogs struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Content     []byte                 `protobuf:"bytes,1,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResponseLogs) Reset() {
	*x = ResponseLogs{}
	mi := &file_proto_process_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseLogs) ProtoMessage() {}

func (x *ResponseLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseLogs) GetContent() []byte {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *ResponseLogs) SetContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ResponseLogs) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResponseLogs) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Content = nil
}

type ResponseLogs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Content []byte
}

func (b0 ResponseLogs_builder) Build() *ResponseLogs {
	m0 := &ResponseLogs{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

type RequestWatchLogs struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestWatchLogs) Reset() {
	*x = RequestWatchLogs{}
	mi := &file_proto_process_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWatchLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWatchLogs) ProtoMessage() {}

func (x *RequestWatchLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RequestWatchLogs) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RequestWatchLogs) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RequestWatchLogs) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RequestWatchLogs) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type RequestWatchLogs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 RequestWatchLogs_builder) Build() *RequestWatchLogs {
	m0 := &RequestWatchLogs{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type ResponseWatchLogs struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Content     []byte                 `protobuf:"bytes,1,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResponseWatchLogs) Reset() {
	*x = ResponseWatchLogs{}
	mi := &file_proto_process_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseWatchLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWatchLogs) ProtoMessage() {}

func (x *ResponseWatchLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseWatchLogs) GetContent() []byte {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *ResponseWatchLogs) SetContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ResponseWatchLogs) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResponseWatchLogs) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Content = nil
}

type ResponseWatchLogs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Content []byte
}

func (b0 ResponseWatchLogs_builder) Build() *ResponseWatchLogs {
	m0 := &ResponseWatchLogs{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

type RequestWatchStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWatchStatus) Reset() {
	*x = RequestWatchStatus{}
	mi := &file_proto_process_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWatchStatus) ProtoMessage() {}

func (x *RequestWatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RequestWatchStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RequestWatchStatus_builder) Build() *RequestWatchStatus {
	m0 := &RequestWatchStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResponseWatchStatus struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Processes *[]*ProcessStatus      `protobuf:"bytes,1,rep,name=processes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResponseWatchStatus) Reset() {
	*x = ResponseWatchStatus{}
	mi := &file_proto_process_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseWatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWatchStatus) ProtoMessage() {}

func (x *ResponseWatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_process_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseWatchStatus) GetProcesses() []*ProcessStatus {
	if x != nil {
		if x.xxx_hidden_Processes != nil {
			return *x.xxx_hidden_Processes
		}
	}
	return nil
}

func (x *ResponseWatchStatus) SetProcesses(v []*ProcessStatus) {
	x.xxx_hidden_Processes = &v
}

type ResponseWatchStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Processes []*ProcessStatus
}

func (b0 ResponseWatchStatus_builder) Build() *ResponseWatchStatus {
	m0 := &ResponseWatchStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Processes = &b.Processes
	return m0
}

var File_proto_process_proto protoreflect.FileDescriptor

const file_proto_process_proto_rawDesc = "" +
	"\n" +
	"\x13proto/process.proto\x12\aprocess\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\aProcess\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x19\n" +
	"\blog_file\x18\x04 \x01(\tR\alogFile\x12\x14\n" +
	"\x05watch\x18\x05 \x01(\bR\x05watch\"\x8b\x01\n" +
	"\rProcessStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12+\n" +
	"\x05state\x18\x03 \x01(\x0e2\x15.process.ProcessStateR\x05state\"#\n" +
	"\rRequestStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x0eResponseStatus\x124\n" +
	"\tprocesses\x18\x01 \x03(\v2\x16.process.ProcessStatusR\tprocesses\"\"\n" +
	"\fRequestStart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1f\n" +
	"\rResponseStart\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"!\n" +
	"\vRequestStop\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\fResponseStop\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"$\n" +
	"\x0eRequestRestart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x11\n" +
	"\x0fResponseRestart\"!\n" +
	"\vRequestLogs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fResponseLogs\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"&\n" +
	"\x10RequestWatchLogs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x11ResponseWatchLogs\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\x14\n" +
	"\x12RequestWatchStatus\"K\n" +
	"\x13ResponseWatchStatus\x124\n" +
	"\tprocesses\x18\x01 \x03(\v2\x16.process.ProcessStatusR\tprocesses*}\n" +
	"\fProcessState\x12\x19\n" +
	"\x15PROCESS_STATE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12PROCESS_STATE_STOP\x10\x01\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bPROCESS_STATE_NEEDS_RESTART\x10\x032\xbd\x03\n" +
	"\x0eProcessManager\x129\n" +
	"\x06Status\x12\x16.process.RequestStatus\x1a\x17.process.ResponseStatus\x12J\n" +
	"\vWatchStatus\x12\x1b.process.RequestWatchStatus\x1a\x1c.process.ResponseWatchStatus0\x01\x126\n" +
	"\x05Start\x12\x15.process.RequestStart\x1a\x16.process.ResponseStart\x123\n" +
	"\x04Stop\x12\x14.process.RequestStop\x1a\x15.process.ResponseStop\x12<\n" +
	"\aRestart\x12\x17.process.RequestRestart\x1a\x18.process.ResponseRestart\x123\n" +
	"\x04Logs\x12\x14.process.RequestLogs\x1a\x15.process.ResponseLogs\x12D\n" +
	"\tWatchLogs\x12\x19.process.RequestWatchLogs\x1a\x1a.process.ResponseWatchLogs0\x01B/Z#go.f110.dev/ProcessManagerBar/proto\x92\x03\a\xd2>\x02\x10\x03\b\x01b\beditionsp\xe9\a"

var file_proto_process_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_process_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_process_proto_goTypes = []any{
	(ProcessState)(0),             // 0: process.ProcessState
	(*Process)(nil),               // 1: process.Process
	(*ProcessStatus)(nil),         // 2: process.ProcessStatus
	(*RequestStatus)(nil),         // 3: process.RequestStatus
	(*ResponseStatus)(nil),        // 4: process.ResponseStatus
	(*RequestStart)(nil),          // 5: process.RequestStart
	(*ResponseStart)(nil),         // 6: process.ResponseStart
	(*RequestStop)(nil),           // 7: process.RequestStop
	(*ResponseStop)(nil),          // 8: process.ResponseStop
	(*RequestRestart)(nil),        // 9: process.RequestRestart
	(*ResponseRestart)(nil),       // 10: process.ResponseRestart
	(*RequestLogs)(nil),           // 11: process.RequestLogs
	(*ResponseLogs)(nil),          // 12: process.ResponseLogs
	(*RequestWatchLogs)(nil),      // 13: process.RequestWatchLogs
	(*ResponseWatchLogs)(nil),     // 14: process.ResponseWatchLogs
	(*RequestWatchStatus)(nil),    // 15: process.RequestWatchStatus
	(*ResponseWatchStatus)(nil),   // 16: process.ResponseWatchStatus
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_proto_process_proto_depIdxs = []int32{
	17, // 0: process.ProcessStatus.started_at:type_name -> google.protobuf.Timestamp
	0,  // 1: process.ProcessStatus.state:type_name -> process.ProcessState
	2,  // 2: process.ResponseStatus.processes:type_name -> process.ProcessStatus
	2,  // 3: process.ResponseWatchStatus.processes:type_name -> process.ProcessStatus
	3,  // 4: process.ProcessManager.Status:input_type -> process.RequestStatus
	15, // 5: process.ProcessManager.WatchStatus:input_type -> process.RequestWatchStatus
	5,  // 6: process.ProcessManager.Start:input_type -> process.RequestStart
	7,  // 7: process.ProcessManager.Stop:input_type -> process.RequestStop
	9,  // 8: process.ProcessManager.Restart:input_type -> process.RequestRestart
	11, // 9: process.ProcessManager.Logs:input_type -> process.RequestLogs
	13, // 10: process.ProcessManager.WatchLogs:input_type -> process.RequestWatchLogs
	4,  // 11: process.ProcessManager.Status:output_type -> process.ResponseStatus
	16, // 12: process.ProcessManager.WatchStatus:output_type -> process.ResponseWatchStatus
	6,  // 13: process.ProcessManager.Start:output_type -> process.ResponseStart
	8,  // 14: process.ProcessManager.Stop:output_type -> process.ResponseStop
	10, // 15: process.ProcessManager.Restart:output_type -> process.ResponseRestart
	12, // 16: process.ProcessManager.Logs:output_type -> process.ResponseLogs
	14, // 17: process.ProcessManager.WatchLogs:output_type -> process.ResponseWatchLogs
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_process_proto_init() }
func file_proto_process_proto_init() {
	if File_proto_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_process_proto_rawDesc), len(file_proto_process_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_process_proto_goTypes,
		DependencyIndexes: file_proto_process_proto_depIdxs,
		EnumInfos:         file_proto_process_proto_enumTypes,
		MessageInfos:      file_proto_process_proto_msgTypes,
	}.Build()
	File_proto_process_proto = out.File
	file_proto_process_proto_goTypes = nil
	file_proto_process_proto_depIdxs = nil
}
