// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/process.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessManager_Status_FullMethodName    = "/process.ProcessManager/Status"
	ProcessManager_Start_FullMethodName     = "/process.ProcessManager/Start"
	ProcessManager_Stop_FullMethodName      = "/process.ProcessManager/Stop"
	ProcessManager_Restart_FullMethodName   = "/process.ProcessManager/Restart"
	ProcessManager_Logs_FullMethodName      = "/process.ProcessManager/Logs"
	ProcessManager_WatchLogs_FullMethodName = "/process.ProcessManager/WatchLogs"
)

// ProcessManagerClient is the client API for ProcessManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessManagerClient interface {
	Status(ctx context.Context, in *RequestStatus, opts ...grpc.CallOption) (*ResponseStatus, error)
	Start(ctx context.Context, in *RequestStart, opts ...grpc.CallOption) (*ResponseStart, error)
	Stop(ctx context.Context, in *RequestStop, opts ...grpc.CallOption) (*ResponseStop, error)
	Restart(ctx context.Context, in *RequestRestart, opts ...grpc.CallOption) (*ResponseRestart, error)
	Logs(ctx context.Context, in *RequestLogs, opts ...grpc.CallOption) (*ResponseLogs, error)
	WatchLogs(ctx context.Context, in *RequestWatchLogs, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseWatchLogs], error)
}

type processManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessManagerClient(cc grpc.ClientConnInterface) ProcessManagerClient {
	return &processManagerClient{cc}
}

func (c *processManagerClient) Status(ctx context.Context, in *RequestStatus, opts ...grpc.CallOption) (*ResponseStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, ProcessManager_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processManagerClient) Start(ctx context.Context, in *RequestStart, opts ...grpc.CallOption) (*ResponseStart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseStart)
	err := c.cc.Invoke(ctx, ProcessManager_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processManagerClient) Stop(ctx context.Context, in *RequestStop, opts ...grpc.CallOption) (*ResponseStop, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseStop)
	err := c.cc.Invoke(ctx, ProcessManager_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processManagerClient) Restart(ctx context.Context, in *RequestRestart, opts ...grpc.CallOption) (*ResponseRestart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseRestart)
	err := c.cc.Invoke(ctx, ProcessManager_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processManagerClient) Logs(ctx context.Context, in *RequestLogs, opts ...grpc.CallOption) (*ResponseLogs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseLogs)
	err := c.cc.Invoke(ctx, ProcessManager_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processManagerClient) WatchLogs(ctx context.Context, in *RequestWatchLogs, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseWatchLogs], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessManager_ServiceDesc.Streams[0], ProcessManager_WatchLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestWatchLogs, ResponseWatchLogs]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessManager_WatchLogsClient = grpc.ServerStreamingClient[ResponseWatchLogs]

// ProcessManagerServer is the server API for ProcessManager service.
// All implementations must embed UnimplementedProcessManagerServer
// for forward compatibility.
type ProcessManagerServer interface {
	Status(context.Context, *RequestStatus) (*ResponseStatus, error)
	Start(context.Context, *RequestStart) (*ResponseStart, error)
	Stop(context.Context, *RequestStop) (*ResponseStop, error)
	Restart(context.Context, *RequestRestart) (*ResponseRestart, error)
	Logs(context.Context, *RequestLogs) (*ResponseLogs, error)
	WatchLogs(*RequestWatchLogs, grpc.ServerStreamingServer[ResponseWatchLogs]) error
	mustEmbedUnimplementedProcessManagerServer()
}

// UnimplementedProcessManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessManagerServer struct{}

func (UnimplementedProcessManagerServer) Status(context.Context, *RequestStatus) (*ResponseStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedProcessManagerServer) Start(context.Context, *RequestStart) (*ResponseStart, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedProcessManagerServer) Stop(context.Context, *RequestStop) (*ResponseStop, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedProcessManagerServer) Restart(context.Context, *RequestRestart) (*ResponseRestart, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedProcessManagerServer) Logs(context.Context, *RequestLogs) (*ResponseLogs, error) {
	return nil, status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedProcessManagerServer) WatchLogs(*RequestWatchLogs, grpc.ServerStreamingServer[ResponseWatchLogs]) error {
	return status.Error(codes.Unimplemented, "method WatchLogs not implemented")
}
func (UnimplementedProcessManagerServer) mustEmbedUnimplementedProcessManagerServer() {}
func (UnimplementedProcessManagerServer) testEmbeddedByValue()                        {}

// UnsafeProcessManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessManagerServer will
// result in compilation errors.
type UnsafeProcessManagerServer interface {
	mustEmbedUnimplementedProcessManagerServer()
}

func RegisterProcessManagerServer(s grpc.ServiceRegistrar, srv ProcessManagerServer) {
	// If the following call panics, it indicates UnimplementedProcessManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessManager_ServiceDesc, srv)
}

func _ProcessManager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessManager_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessManagerServer).Status(ctx, req.(*RequestStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessManager_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessManagerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessManager_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessManagerServer).Start(ctx, req.(*RequestStart))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessManager_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessManagerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessManager_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessManagerServer).Stop(ctx, req.(*RequestStop))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessManager_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRestart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessManagerServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessManager_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessManagerServer).Restart(ctx, req.(*RequestRestart))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessManager_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLogs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessManagerServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessManager_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessManagerServer).Logs(ctx, req.(*RequestLogs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessManager_WatchLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestWatchLogs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessManagerServer).WatchLogs(m, &grpc.GenericServerStream[RequestWatchLogs, ResponseWatchLogs]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessManager_WatchLogsServer = grpc.ServerStreamingServer[ResponseWatchLogs]

// ProcessManager_ServiceDesc is the grpc.ServiceDesc for ProcessManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "process.ProcessManager",
	HandlerType: (*ProcessManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ProcessManager_Status_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _ProcessManager_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ProcessManager_Stop_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _ProcessManager_Restart_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _ProcessManager_Logs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchLogs",
			Handler:       _ProcessManager_WatchLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/process.proto",
}
